### ISSUE TITLE
更新版本后报错: ImportError: cannot import name 'display_style' from 'colort'

### ISSUE THREAD

**Issue by n1k0ver3E** [up2b/pyup2b#11]
Python Version: 3.9/ 3.12.2 均报错，导致无法启动。

```
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/bin/up2b", line 5, in <module>
    from up2b import run_main
  File "/Users/xxx/miniconda3/lib/python3.12/site-packages/up2b/__init__.py", line 15, in <module>
    from colort import display_style as ds
ImportError: cannot import name 'display_style' from 'colort' (/Users/xxx/miniconda3/lib/python3.12/site-packages/colort/__init__.py)
```

**Comment by thep0y** [comment]
安装最新的测试版试试。

```bash
pip install up2b==0.7.1b0
```

**Comment by n1k0ver3E** [comment]
更新了一下好像还是有点问题，
<img width="1099" alt="image" src="https://github.com/up2b/pyup2b/assets/14194564/91e644b8-a3f1-4441-a8d6-766ac1b05bc6">

```
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/envs/up2b-test/bin/up2b", line 5, in <module>
    from up2b import run_main
  File "/Users/xxx/miniconda3/envs/up2b-test/lib/python3.12/site-packages/up2b/__init__.py", line 72, in <module>
    @cli.command(
     ^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/up2b-test/lib/python3.12/site-packages/click/core.py", line 1887, in decorator
    cmd: Command = command(*args, **kwargs)(f)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/up2b-test/lib/python3.12/site-packages/click/decorators.py", line 218, in decorator
    raise TypeError("Attempted to convert a callback into a command twice.")
TypeError: Attempted to convert a callback into a command twice.
```

**Comment by n1k0ver3E** [comment]
您有空可以看看这个bug，不过这边typora的uploader 已经恢复。
up2b version: 0.7.1b0
python version: 3.12.2

**Comment by thep0y** [comment]
经测试，无法复现问题。

即此bug应与本程序无关。

<details>

<summary>复现过程</summary>

```
$ conda create -n test python=3.12                      (base)
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate test                                   (base)
$ pip install up2b==0.7.1b0                             (test)
...
Successfully installed certifi-2024.6.2 charset-normalizer-3.3.2 click-8.1.7 colorful-logger-0.2.0b6 colort-1.0.1 idna-3.7 requests-2.32.3 requests-toolbelt-1.0.0 tqdm-4.66.4 up2b-0.7.1b0 urllib3-2.2.1
$ up2b -h                                               (test)
Usage: up2b [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help     显示本帮助信息
  -v, --version  显示版本信息

Commands:
  add-cache         手动添加缓存
  choose            选择图床
  config-watermark  配置文字水印
  current           显示正在使用的图床
  list              列出支持的所有图床
  login             保存图床登录信息
  login-git         保存 git 登录信息
  upload            上传图片
$ up2b -v                                               (test)
0.7.1b0
$ up2b                                                  (test)
Usage: up2b [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help     显示本帮助信息
  -v, --version  显示版本信息

Commands:
  add-cache         手动添加缓存
  choose            选择图床
  config-watermark  配置文字水印
  current           显示正在使用的图床
  list              列出支持的所有图床
  login             保存图床登录信息
  login-git         保存 git 登录信息
  upload            上传图片
```
</details>

**Comment by n1k0ver3E** [comment]
Ok, 那我这边close这个issue。谢谢回复
